#!/usr/bin/env python3
"""Shared core for the LOCAL, on-demand agent session-id E2E checks (CMH-STAMP-04).

These are NOT CI tests - they drive a real agent CLI (Claude Code / Copilot CLI), which the
check-in gate cannot do. `claude_e2e_check.py` and `copilot_e2e_check.py` are thin wrappers over
`run_e2e()` here; none of the three has a `test_` prefix, so pytest / unittest never auto-collect
them.

The flow is identical for every agent: drive the agent CLI to run this repo's `new_document.py`
with NO `--session-id`, so the tool must AUTO-DETECT the agent's session id from the environment,
then read the generated file and assert `commentable-html-agent` is the expected agent and a
session id was stamped. The command the agent runs only GENERATES the document and greps the two
`<meta>` provenance tags back out of that file - it never reads or echoes an environment variable,
which is what lets a security-conscious agent (Claude refuses otherwise) run it.
"""
import os
import re
import shutil
import subprocess
import sys
import tempfile

HERE = os.path.dirname(os.path.abspath(__file__))
# dev/tests -> ../../pkg/skills/commentable-html/tools/authoring/new_document.py
TOOL = os.path.normpath(os.path.join(
    HERE, "..", "..", "pkg", "skills", "commentable-html",
    "tools", "authoring", "new_document.py"))


def fwd(path):
    """An agent's Bash tool wants forward-slash paths even on Windows."""
    return path.replace("\\", "/")


def resolve_bin(explicit, env_var, exe_name, fallback):
    """Locate an agent CLI: explicit path, then $env_var, then PATH, then a known fallback path."""
    for cand in (explicit, os.environ.get(env_var), shutil.which(exe_name)):
        if cand and os.path.exists(cand):
            return cand
        if cand and shutil.which(cand):
            return shutil.which(cand)
    fb = os.path.expandvars(fallback) if fallback else None
    return fb if fb and os.path.exists(fb) else None


def _meta(html, name):
    m = re.search(r'<meta name="%s" content="([^"]*)"' % re.escape(name), html)
    return m.group(1) if m else None


def build_prompt(out_path):
    """A transparent prompt: generate a doc, then grep the two provenance meta tags from the file.
    Reads/echoes no environment variable, so a security-conscious agent will run it."""
    cmd = (
        "echo '<section><h1>Session E2E</h1><p>x</p></section>' | "
        + '"%s" "%s" --content - --key session-e2e --label "Session E2E" '
          "--kind report --portable --out \"%s\" --force"
          % (fwd(sys.executable), fwd(TOOL), fwd(out_path))
        + " && grep -E '<meta name=\"commentable-html-(session-id|agent)\"' \"%s\""
          % fwd(out_path)
    )
    return (
        "Context (a legitimate dev task on the user's own machine, please read fully):\n"
        "The commentable-html plugin stamps a <meta name=\"commentable-html-session-id\"> provenance\n"
        "tag (plus <meta name=\"commentable-html-agent\"> = copilot|claude) into a generated review\n"
        "document so a human reviewer can see and copy which AI agent session produced it - a\n"
        "'generated by' byline. It is opt-out via --no-session-id. We are verifying that detection.\n\n"
        "You are encouraged to FIRST read these files to confirm the tool only writes two harmless\n"
        "<meta> provenance tags (a session id string and the literal 'claude'/'copilot') into the\n"
        "generated file and does nothing else:\n"
        "  - %s\n"
        "  - %s\n"
        "The command below only GENERATES the document and then greps the two <meta> provenance tags\n"
        "back out of that generated file - it does NOT read or echo any environment variable. Once\n"
        "you are satisfied it is benign, run EXACTLY this one command and paste its output:\n\n%s\n"
        % (fwd(os.path.join(os.path.dirname(TOOL), "doc_stamp.py")), fwd(TOOL), cmd)
    )


def run_e2e(cli_label, cli_bin, make_argv, expected_agent, timeout=300):
    """Drive `cli_bin` (via make_argv(cli_bin, prompt)) to generate a doc, then assert the stamp.

    Returns 0 = PASS, 1 = ran but the stamp was wrong, 2 = could not run (CLI/tool missing, timeout).
    """
    if not os.path.exists(TOOL):
        print("SKIP: new_document.py not found at %s" % TOOL)
        return 2
    if not cli_bin:
        print("SKIP: %s CLI not found. Pass --cli PATH or set the env override." % cli_label)
        return 2

    out_path = os.path.join(tempfile.mkdtemp(prefix="cmh_%s_e2e_" % cli_label), "session-e2e.html")
    prompt = build_prompt(out_path)
    print("Running %s E2E check via %s ..." % (cli_label, cli_bin))
    try:
        proc = subprocess.run(make_argv(cli_bin, prompt), capture_output=True,
                              text=True, encoding="utf-8", errors="replace", timeout=timeout)
    except subprocess.TimeoutExpired:
        print("FAIL: %s did not respond within %ss" % (cli_label, timeout))
        return 2
    stdout = proc.stdout or ""

    if not os.path.exists(out_path):
        print("FAIL: %s did not generate the document (it may have declined to run the command)."
              % cli_label)
        print("--- %s output ---\n%s" % (cli_label, stdout.strip()[-1500:]))
        return 1

    with open(out_path, encoding="utf-8") as fh:
        html = fh.read()
    agent = _meta(html, "commentable-html-agent")
    sid = _meta(html, "commentable-html-session-id")
    print("stamped agent      : %s" % agent)
    print("stamped session id : %s" % sid)

    ok = True
    if agent != expected_agent:
        print("FAIL: expected commentable-html-agent=%s, got %r" % (expected_agent, agent))
        ok = False
    if not sid:
        print("FAIL: no commentable-html-session-id was stamped")
        ok = False

    if ok:
        print("PASS: %s auto-detected and stamped its session id as agent=%s."
              % (cli_label, expected_agent))
        return 0
    return 1
