#!/usr/bin/env python3
"""CMH-REVIEW-08: the JS runtime and the Python helper compute IDENTICAL section hashes.

The committed golden `fixtures/section_hash/golden.json` is generated by the JS implementation
(tests/build_section_hash_golden.mjs, using the same cmhSectionHash as assets/js/84-section-review.js).
This test asserts the Python `section_hash.cmh_section_hash` reproduces every golden hash, and the
Playwright suite (tests/90-section-review.spec.js) asserts the live runtime reproduces the same
golden - so the two implementations are pinned equal and cannot drift.
"""
import json
import os
import sys
import unittest

HERE = os.path.dirname(os.path.abspath(__file__))
import _paths  # noqa: E402
import section_hash  # noqa: E402

GOLDEN = os.path.join(HERE, "fixtures", "section_hash", "golden.json")


class GoldenHashTests(unittest.TestCase):
    def test_python_reproduces_the_js_golden(self):
        with open(GOLDEN, encoding="utf-8") as fh:
            golden = json.load(fh)
        self.assertGreaterEqual(len(golden), 5)
        for entry in golden:
            self.assertEqual(section_hash.cmh_section_hash(entry["text"]), entry["hash"],
                             "hash mismatch for %r" % entry["text"])

    def test_whitespace_is_collapsed(self):
        self.assertEqual(section_hash.cmh_section_hash("a  b\t c\n d"),
                         section_hash.cmh_section_hash("a b c d"))

    def test_empty_is_stable(self):
        self.assertEqual(section_hash.cmh_section_hash(""), section_hash.cmh_section_hash("   "))


class ExtractTests(unittest.TestCase):
    ROOT = '<main id="commentRoot">%s</main>'

    def test_headings_get_ids_levels_text_and_hash(self):
        html = self.ROOT % (
            '<h2 id="a">Goals</h2><p>Goal body text.</p>'
            '<h2 id="b">Plan</h2><p>Plan body text.</p>'
        )
        secs = {s["id"]: s for s in section_hash.extract_sections(html)}
        self.assertEqual(set(secs), {"a", "b"})
        self.assertEqual(secs["a"]["level"], 2)
        self.assertEqual(secs["a"]["headingText"], "Goals")
        self.assertNotEqual(secs["a"]["hash"], secs["b"]["hash"])

    def test_cm_skip_subtree_is_excluded_from_the_hash(self):
        with_skip = self.ROOT % (
            '<h2 id="a">Goals<button class="cm-skip">Mark reviewed</button></h2>'
            '<p>Body.<span class="cm-skip">CHROME</span></p>'
        )
        without = self.ROOT % '<h2 id="a">Goals</h2><p>Body.</p>'
        a1 = {s["id"]: s for s in section_hash.extract_sections(with_skip)}["a"]
        a2 = {s["id"]: s for s in section_hash.extract_sections(without)}["a"]
        self.assertEqual(a1["hash"], a2["hash"])
        self.assertEqual(a1["headingText"], "Goals")  # the cm-skip button text is not in the heading

    def test_section_boundary_is_next_same_or_higher_heading(self):
        # A nested h3 belongs to the h2 section; the next h2 ends it.
        html = self.ROOT % (
            '<h2 id="a">A</h2><p>a-body</p>'
            '<h3 id="a1">A1</h3><p>a1-body</p>'
            '<h2 id="b">B</h2><p>b-body</p>'
        )
        secs = {s["id"]: s for s in section_hash.extract_sections(html)}
        # Section A spans through the nested h3 up to h2 B: changing a1-body changes A's hash.
        html2 = html.replace("a1-body", "a1-CHANGED")
        secs2 = {s["id"]: s for s in section_hash.extract_sections(html2)}
        self.assertNotEqual(secs["a"]["hash"], secs2["a"]["hash"])
        self.assertEqual(secs["b"]["hash"], secs2["b"]["hash"])  # B unaffected

    def test_content_outside_root_is_ignored(self):
        html = '<h2 id="x">Outside</h2>' + self.ROOT % '<h2 id="a">Inside</h2><p>body</p>'
        secs = {s["id"]: s for s in section_hash.extract_sections(html)}
        self.assertEqual(set(secs), {"a"})

    def test_headings_without_ids_are_skipped(self):
        html = self.ROOT % '<h2>No id</h2><p>body</p><h2 id="a">Has id</h2><p>b</p>'
        secs = {s["id"]: s for s in section_hash.extract_sections(html)}
        self.assertEqual(set(secs), {"a"})

    def test_script_style_template_text_is_excluded(self):
        with_inert = self.ROOT % (
            '<h2 id="a">Goals</h2><p>Body.</p>'
            '<style>.x{color:red}</style><script>var q=1;</script>'
            '<template><p>tpl</p></template>'
        )
        without = self.ROOT % '<h2 id="a">Goals</h2><p>Body.</p>'
        a1 = {s["id"]: s for s in section_hash.extract_sections(with_inert)}["a"]
        a2 = {s["id"]: s for s in section_hash.extract_sections(without)}["a"]
        self.assertEqual(a1["hash"], a2["hash"])

    def test_void_cm_skip_element_does_not_suppress_following_text(self):
        # A void cm-skip element (no end tag) must not stay on the parser stack and hide siblings.
        with_void = self.ROOT % '<h2 id="a">Goals</h2><img class="cm-skip" src="x"><p>Body after void.</p>'
        without = self.ROOT % '<h2 id="a">Goals</h2><p>Body after void.</p>'
        a1 = {s["id"]: s for s in section_hash.extract_sections(with_void)}["a"]
        a2 = {s["id"]: s for s in section_hash.extract_sections(without)}["a"]
        self.assertEqual(a1["hash"], a2["hash"])


if __name__ == "__main__":
    unittest.main()
