#!/usr/bin/env python3
"""CMH-REVIEW-08: the JS runtime and the Python helper compute IDENTICAL section hashes.

The committed golden `fixtures/section_hash/golden.json` is generated by the JS implementation
(tests/build_section_hash_golden.mjs, using the same cmhSectionHash as assets/js/84-section-review.js).
This test asserts the Python `section_hash.cmh_section_hash` reproduces every golden hash, and the
Playwright suite (tests/90-section-review.spec.js) asserts the live runtime reproduces the same
golden - so the two implementations are pinned equal and cannot drift.
"""
import json
import os
import sys
import unittest

HERE = os.path.dirname(os.path.abspath(__file__))
import _paths  # noqa: E402
import section_hash  # noqa: E402

GOLDEN = os.path.join(HERE, "fixtures", "section_hash", "golden.json")


class GoldenHashTests(unittest.TestCase):
    def test_python_reproduces_the_js_golden(self):
        with open(GOLDEN, encoding="utf-8") as fh:
            golden = json.load(fh)
        self.assertGreaterEqual(len(golden), 5)
        for entry in golden:
            self.assertEqual(section_hash.cmh_section_hash(entry["text"]), entry["hash"],
                             "hash mismatch for %r" % entry["text"])

    def test_whitespace_is_collapsed(self):
        self.assertEqual(section_hash.cmh_section_hash("a  b\t c\n d"),
                         section_hash.cmh_section_hash("a b c d"))

    def test_empty_is_stable(self):
        self.assertEqual(section_hash.cmh_section_hash(""), section_hash.cmh_section_hash("   "))


class ExtractTests(unittest.TestCase):
    ROOT = '<main id="commentRoot">%s</main>'

    def test_headings_get_ids_levels_text_and_hash(self):
        html = self.ROOT % (
            '<h2 id="a">Goals</h2><p>Goal body text.</p>'
            '<h2 id="b">Plan</h2><p>Plan body text.</p>'
        )
        secs = {s["id"]: s for s in section_hash.extract_sections(html)}
        self.assertEqual(set(secs), {"a", "b"})
        self.assertEqual(secs["a"]["level"], 2)
        self.assertEqual(secs["a"]["headingText"], "Goals")
        self.assertNotEqual(secs["a"]["hash"], secs["b"]["hash"])

    def test_cm_skip_subtree_is_excluded_from_the_hash(self):
        with_skip = self.ROOT % (
            '<h2 id="a">Goals<button class="cm-skip">Mark reviewed</button></h2>'
            '<p>Body.<span class="cm-skip">CHROME</span></p>'
        )
        without = self.ROOT % '<h2 id="a">Goals</h2><p>Body.</p>'
        a1 = {s["id"]: s for s in section_hash.extract_sections(with_skip)}["a"]
        a2 = {s["id"]: s for s in section_hash.extract_sections(without)}["a"]
        self.assertEqual(a1["hash"], a2["hash"])
        self.assertEqual(a1["headingText"], "Goals")  # the cm-skip button text is not in the heading

    def test_section_boundary_is_next_same_or_higher_heading(self):
        # A nested h3 belongs to the h2 section; the next h2 ends it.
        html = self.ROOT % (
            '<h2 id="a">A</h2><p>a-body</p>'
            '<h3 id="a1">A1</h3><p>a1-body</p>'
            '<h2 id="b">B</h2><p>b-body</p>'
        )
        secs = {s["id"]: s for s in section_hash.extract_sections(html)}
        # Section A spans through the nested h3 up to h2 B: changing a1-body changes A's hash.
        html2 = html.replace("a1-body", "a1-CHANGED")
        secs2 = {s["id"]: s for s in section_hash.extract_sections(html2)}
        self.assertNotEqual(secs["a"]["hash"], secs2["a"]["hash"])
        self.assertEqual(secs["b"]["hash"], secs2["b"]["hash"])  # B unaffected

    def test_content_outside_root_is_ignored(self):
        html = '<h2 id="x">Outside</h2>' + self.ROOT % '<h2 id="a">Inside</h2><p>body</p>'
        secs = {s["id"]: s for s in section_hash.extract_sections(html)}
        self.assertEqual(set(secs), {"a"})

    def test_headings_without_ids_are_skipped(self):
        html = self.ROOT % '<h2>No id</h2><p>body</p><h2 id="a">Has id</h2><p>b</p>'
        secs = {s["id"]: s for s in section_hash.extract_sections(html)}
        self.assertEqual(set(secs), {"a"})

    def test_script_style_template_text_is_excluded(self):
        with_inert = self.ROOT % (
            '<h2 id="a">Goals</h2><p>Body.</p>'
            '<style>.x{color:red}</style><script>var q=1;</script>'
            '<template><p>tpl</p></template>'
        )
        without = self.ROOT % '<h2 id="a">Goals</h2><p>Body.</p>'
        a1 = {s["id"]: s for s in section_hash.extract_sections(with_inert)}["a"]
        a2 = {s["id"]: s for s in section_hash.extract_sections(without)}["a"]
        self.assertEqual(a1["hash"], a2["hash"])

    def test_void_cm_skip_element_does_not_suppress_following_text(self):
        # A void cm-skip element (no end tag) must not stay on the parser stack and hide siblings.
        with_void = self.ROOT % '<h2 id="a">Goals</h2><img class="cm-skip" src="x"><p>Body after void.</p>'
        without = self.ROOT % '<h2 id="a">Goals</h2><p>Body after void.</p>'
        a1 = {s["id"]: s for s in section_hash.extract_sections(with_void)}["a"]
        a2 = {s["id"]: s for s in section_hash.extract_sections(without)}["a"]
        self.assertEqual(a1["hash"], a2["hash"])


class DocumentContentHashTests(unittest.TestCase):
    """CMH-STAMP-05: document_content_hash is the whole content-root text hashed once with the same
    FNV-1a and exclusion contract as the section hashes, so the runtime (cmhDocContentHash) and this
    Python helper agree byte for byte and a post-validation edit is detectable."""

    ROOT = '<main id="commentRoot">%s</main>'

    def test_matches_the_shared_hash_over_the_content_root_text(self):
        html = self.ROOT % "<p>Hello world</p>"
        self.assertEqual(section_hash.document_content_hash(html),
                         section_hash.cmh_section_hash("Hello world"))

    def test_hash_changes_when_content_changes(self):
        a = section_hash.document_content_hash(self.ROOT % "<p>one</p>")
        b = section_hash.document_content_hash(self.ROOT % "<p>two</p>")
        self.assertNotEqual(a, b)

    def test_hash_excludes_cm_skip_and_runtime_transformed_blocks(self):
        base = section_hash.document_content_hash(self.ROOT % "<p>keep this prose</p>")
        noisy = section_hash.document_content_hash(self.ROOT % (
            '<p>keep this prose</p>'
            '<div class="cm-skip">injected chrome</div>'
            '<pre class="mermaid">graph TD; a-->b</pre>'
            '<pre class="cmh-diff">- old\n+ new</pre>'
            '<canvas>chart</canvas>'))
        self.assertEqual(base, noisy, "chrome and runtime-transformed blocks must not affect the hash")

    def test_hash_is_none_without_a_content_root(self):
        self.assertIsNone(section_hash.document_content_hash("<body><p>no root</p></body>"))

    def test_hashes_only_the_first_commentRoot(self):
        # The runtime hashes getElementById("commentRoot") - a single subtree. A trailing second
        # content root must NOT be folded in (Python previously re-opened on any later root).
        a = section_hash.document_content_hash('<main id="commentRoot">A</main>')
        b = section_hash.document_content_hash(
            '<main id="commentRoot">A</main><aside data-cmh-content-root>B</aside>')
        self.assertEqual(a, b)

    def test_a_template_parked_root_does_not_hide_the_live_root(self):
        html = ('<template><main id="commentRoot">Hidden</main></template>'
                '<main id="commentRoot">Real</main>')
        self.assertEqual(section_hash.document_content_hash(html),
                         section_hash.cmh_section_hash("Real"))

    def test_only_id_commentRoot_is_the_root_not_a_bare_data_attr(self):
        # A bare data-cmh-content-root is not getElementById("commentRoot"); only id=commentRoot is.
        self.assertIsNone(section_hash.document_content_hash('<aside data-cmh-content-root>X</aside>'))
        both = section_hash.document_content_hash(
            '<aside data-cmh-content-root>DECOY</aside><main id="commentRoot">real</main>')
        self.assertEqual(both, section_hash.cmh_section_hash("real"))

    def test_noscript_is_excluded(self):
        # With scripting ON the browser exposes <noscript> markup as literal text; excluding it on
        # both sides keeps the Python and runtime hashes in agreement.
        base = section_hash.document_content_hash(self.ROOT % "<p>keep</p>")
        withns = section_hash.document_content_hash(
            self.ROOT % "<p>keep</p><noscript><b>enable JS</b></noscript>")
        self.assertEqual(base, withns)

    def test_hash_covers_the_whole_document_not_a_single_section(self):
        # Editing prose in ANY section changes the whole-document hash.
        one = self.ROOT % '<h2 id="a">A</h2><p>alpha</p><h2 id="b">B</h2><p>beta</p>'
        two = self.ROOT % '<h2 id="a">A</h2><p>alpha</p><h2 id="b">B</h2><p>BETA-CHANGED</p>'
        self.assertNotEqual(section_hash.document_content_hash(one),
                            section_hash.document_content_hash(two))


class HeadingBoundaryTests(unittest.TestCase):
    """CMH-VAL-21: the section extractor ends a heading (and the content root it lives in) exactly
    where the validator's `_DocParser` ends it, so a truncated or ancestor-closed document is ONE
    document to the validator and to this authoring tool."""

    ROOT = '<main id="commentRoot">%s</main>'

    def test_a_heading_left_open_at_end_of_input_is_closed_by_the_parser(self):
        # The parser itself owns the end-of-input boundary; a caller must not have to guess it.
        parser = section_hash._SectionParser()
        parser.feed(self.ROOT[:-7] % '<h2 id="a">Alpha</h2><h2 id="b">Beta')
        parser.close()
        self.assertEqual([h["end"] for h in parser.headings][-1], parser.length)

    def test_an_ancestor_closing_over_the_root_ends_the_section(self):
        # </section> closes over an unterminated #commentRoot, so the last section stops there
        # instead of absorbing the text a browser puts outside the root. (Verified in chromium:
        # `getElementById("commentRoot").textContent` is "keep" for the trailing-prose document.)
        open_root = '<section><main id="commentRoot"><h2 id="a">Alpha</h2><p>inside</p>'
        clean = section_hash.extract_sections(open_root + "</section>")
        trailing = section_hash.extract_sections(
            open_root + "</section><p>outside trailing prose</p>")
        self.assertEqual([s["hash"] for s in clean], [s["hash"] for s in trailing])

    def test_a_heading_outside_a_root_an_ancestor_closed_is_not_a_section(self):
        secs = section_hash.extract_sections(
            '<section><main id="commentRoot"><h2 id="a">Alpha</h2></section><h2 id="c">Gamma</h2>')
        self.assertEqual([s["id"] for s in secs], ["a"])

    def test_the_document_hash_stops_where_an_ancestor_closes_the_root(self):
        open_root = '<section><main id="commentRoot"><p>keep</p>'
        clean = section_hash.document_content_hash(open_root + "</section>")
        trailing = section_hash.document_content_hash(open_root + "</section><p>outside</p>")
        self.assertEqual(clean, trailing)

    def test_an_after_body_end_tag_does_not_end_the_root(self):
        # HTML5 does not POP for </body> or </html> - they switch the insertion mode, and what
        # follows is appended to the element still open. Verified in chromium: for
        # `<body><main id="commentRoot"><p>keep</p></body><p>outside</p>` the root's textContent
        # is "keepoutside". The runtime hashes that, so this parser must too.
        open_root = '<body><main id="commentRoot"><p>keep</p>'
        self.assertEqual(section_hash.document_content_hash(open_root + "</body><p>outside</p>"),
                         section_hash.cmh_section_hash("keepoutside"))
        self.assertEqual(section_hash.document_content_hash(
            '<html><body><main id="commentRoot"><p>keep</p></html><p>outside</p>'),
            section_hash.cmh_section_hash("keepoutside"))

    def test_a_heading_after_an_after_body_end_tag_is_still_a_section(self):
        secs = section_hash.extract_sections(
            '<body><main id="commentRoot"><h2 id="a">Alpha</h2></body><h2 id="c">Gamma</h2>')
        self.assertEqual([s["id"] for s in secs], ["a", "c"])

    def test_a_block_start_closes_an_open_cm_skip_paragraph(self):
        html = ('<main id="commentRoot"><p class="cm-skip">Hidden'
                '<h2 id="shown">Shown</h2><p>Body</p></main>')
        secs = {s["id"]: s for s in section_hash.extract_sections(html)}
        self.assertEqual(list(secs), ["shown"])
        self.assertEqual(secs["shown"]["headingText"], "Shown")
        self.assertEqual(section_hash.document_content_hash(html),
                         section_hash.cmh_section_hash("ShownBody"))

    def test_a_new_list_item_closes_an_open_cm_skip_item(self):
        html = ('<main id="commentRoot"><ul><li class="cm-skip">Hidden'
                '<li><h2 id="shown">Shown</h2><p>Body</p></ul></main>')
        secs = {s["id"]: s for s in section_hash.extract_sections(html)}
        self.assertEqual(list(secs), ["shown"])
        self.assertEqual(section_hash.document_content_hash(html),
                         section_hash.cmh_section_hash("ShownBody"))

    def test_a_self_closing_nonvoid_html_heading_opens_normally(self):
        html = '<main id="commentRoot"><h2 id="shown"/>Shown</h2><p>Body</p></main>'
        secs = {s["id"]: s for s in section_hash.extract_sections(html)}
        self.assertEqual(list(secs), ["shown"])
        self.assertEqual(secs["shown"]["headingText"], "Shown")

    def test_a_heading_quoted_in_rcdata_is_not_a_section(self):
        html = ('<main id="commentRoot"><textarea><h2 id="ghost">Ghost</h2></textarea>'
                '<h2 id="shown">Shown</h2></main>')
        secs = {s["id"]: s for s in section_hash.extract_sections(html)}
        self.assertEqual(list(secs), ["shown"])
        self.assertEqual(secs["shown"]["headingText"], "Shown")

    def test_rcdata_references_match_dom_text_content(self):
        html = '<main id="commentRoot"><textarea>Fish &amp; Chips</textarea></main>'
        self.assertEqual(section_hash.document_content_hash(html),
                         section_hash.cmh_section_hash("Fish & Chips"))

    def test_the_first_lf_after_textarea_is_ignored_like_the_dom(self):
        html = '<main id="commentRoot"><textarea>\nBody</textarea></main>'
        self.assertEqual(section_hash.document_content_hash(html),
                         section_hash.cmh_section_hash("Body"))

    def test_the_first_lf_after_pre_is_ignored_like_the_dom(self):
        html = '<main id="commentRoot"><span>Shown</span><pre>\nBody</pre></main>'
        self.assertEqual(section_hash.document_content_hash(html),
                         section_hash.cmh_section_hash("ShownBody"))

    def test_a_foreign_html_end_tag_closes_the_real_foreign_element(self):
        html = ('<main id="commentRoot"><svg><html class="cm-skip">Hidden</html>'
                '<text>Visible</text></svg></main>')
        self.assertEqual(section_hash.document_content_hash(html),
                         section_hash.cmh_section_hash("Visible"))

    def test_a_heading_the_parser_did_not_hash_is_still_popped(self):
        # The pop is STRUCTURAL: a browser pops any open h1-h6 that is the current node, so a
        # heading excluded from the hash still ends there. Keyed on `hidx` instead, an
        # unterminated cm-skip heading stayed open and the visible heading after it inherited the
        # skip, dropping its section and its text from the document hash. Verified in chromium:
        # the root text is "HiddenShown" and `#v.closest(".cm-skip")` is null.
        for html in ('<main id="commentRoot"><h2 class="cm-skip">Hidden<h2 id="v">Shown</h2></main>',
                     '<main id="commentRoot"><h4 class="cm-skip">Hidden<h2 id="v">Shown</h2></main>'):
            with self.subTest(html=html):
                secs = {s["id"]: s for s in section_hash.extract_sections(html)}
                self.assertEqual(list(secs), ["v"])
                self.assertEqual(secs["v"]["headingText"], "Shown")
                self.assertEqual(section_hash.document_content_hash(html),
                                 section_hash.cmh_section_hash("Shown"))

    def test_a_heading_that_is_not_the_current_node_is_not_popped(self):
        # Verified in chromium: with an open <span> as the current node the new heading nests
        # inside it, so the outer heading is not popped and its text runs on.
        secs = {s["id"]: s for s in section_hash.extract_sections(
            '<main id="commentRoot"><h2 id="a">A<span><h2 id="v">V</h2></span></main>')}
        self.assertEqual(secs["a"]["headingText"], "AV")

    def test_a_new_heading_start_ends_the_open_ones_text(self):
        # HTML5's h1-h6 rule: a new heading pops an open one, so the first heading's text is its
        # own - not its own plus everything the unterminated element ran on to collect.
        secs = {s["id"]: s for s in section_hash.extract_sections(
            self.ROOT % '<h2 id="a">Alpha<h2 id="b">Beta</h2><p>body</p>')}
        self.assertEqual(secs["a"]["headingText"], "Alpha")
        self.assertEqual(secs["b"]["headingText"], "Beta")

    def test_an_ancestors_end_tag_ends_the_headings_own_text(self):
        secs = {s["id"]: s for s in section_hash.extract_sections(
            self.ROOT % '<section><h2 id="a">Alpha</section><p>loose prose</p>')}
        self.assertEqual(secs["a"]["headingText"], "Alpha")


if __name__ == "__main__":
    unittest.main()
